### ISSUE TITLE
Adding standard UI sounds 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/proportion#13]
@jbphet @zepumph 
Please also add the standard UI sounds to the radio buttons, the reset all button, and the pickup/drop of the freely moving objects, as well as the screen selection buttons.

Note - the tolerance slider is just to support design, it will not be in a final version of the sim, so don't add sound to that slider.

**Comment by zepumph** [comment]
@jbphet and I turned on build in UI sounds yesterday. We can add the pickup/drop sound next.

**Comment by jbphet** [comment]
@zepumph and I worked on this together today and the sounds are now all in place with the exception of the grab/release sounds for the second screen, which @zepumph said he'll take care of.  Unassigning.

**Comment by zepumph** [comment]
We will next add this to the bar screen too.

**Comment by zepumph** [comment]
KeyboardDragListener fires start/end for each arrow key interaction. This made grab/release sounds feel really weird, so I moved them instead to be based on focus/blur events. This sounds much nicer. I also added these to the bar screen. This issue is ready for review.

**Comment by zepumph** [comment]
From design meeting, let's take out the pickup and drop sounds from the bar screen.
