### ISSUE TITLE
Does the sim/tool treat a:b as equal to b:a as “success”?

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/proportion#15]
From the design doc:

Does the tool treat a:b as equal to b:a as “success”? (need to consider pedagogical needs, pair interactions, and description/sound cueing needs)

**(4/10/2020) Currently A:B and B:A give success.**

Quote from Dor on Github Issue #7 :
>“* Tradeoff 1: having both a:b and b:a green means that, on average over many users, you’ll happened to find your first green faster, which is good for retention (keeping people un-frustrated).
*Tradeoff 2: Arguably, there is some conceptual gain in noticing both a:b and b:a, because then you are likely to ask yourself “In what sense are these how things the same such that they are both green?"”

Emily:
> seems like Dor has always gone with a:b =/ b:a (from my read of the github issue). That’s fine with me if we have good reason to go with that. An alternative is for the sim to support both options, which could be scaffolded through the use of later screens, by an option to change the “mode” of the sim etc. I wouldn’t want to do that unless there was a very strong case for it. In the absence of that, a:b =/ b:a probably simplifies some aspects of design, and may support learners in figuring out their first ratio faster...which is a big concern for me. If learners don’t begin to conceptually “get” that first ratio relatively quickly (whatever that looks like for middle schoolers) then they won’t keep exploring the sim. A:b = b:a may get them success feedback faster, but seems to me it could muddy the waters as they try to figure out the overall pattern.

Dor's response:
>I am worried by the conceptual entailment of a:b=b:a. I would vote it down.

A quick thought from me: 
Should we differentiate the bars/objects in any way? As soon as we no longer treat them equally, they may require different description. We’re imposing a left-right structure where left and right are distinct, but does that carry over? Or do they receive labels like Bar 1 & Bar 2?

If we come to consensus, I will assign @zepumph to make a change.

**Comment by BLFiedler** [comment]
Dor (from Design Doc)
>Our approach to the Bars situation should be as a direct continuation of the cursors-only. Think of bars as turning location (my hand is 'here') to quantity (my hand is 'so' far from the bottom). To the extent possible, students should be moving from cursors-only to bars to bars-and-grid to bars-and-grid-and-numbers to 'driver' (if we choose to use that) as a continuity of concatenated experiences, ideally in that order, but also with flexibility of going back and forth.

**Comment by amanda-phet** [comment]
>Dor's response:

>>I am worried by the conceptual entailment of a:b=b:a. I would vote it down.

I 100% agree here and would vote for the sim to only treat a:b=a:b as a success.

**Comment by emily-phet** [comment]
@zepumph Please go back to having a:b not equal to b:a, on all screens. Apologies for assuming it should be the other way!

**Comment by emily-phet** [comment]
@Matthew-Moore240 Please note this change, this is not as I described it to you last week. Once @zepumph makes this change, the sim will work like this - for the ratio 1:2, the right side will have to be twice as high as the left side to get "success" feedback. If the left side is twice as high as the right, no success. So a:b ratio will not equal b:a ratio in the sim.

**Comment by zepumph** [comment]
Sounds good! Implemented above. @Matthew-Moore240 feel free to close once you have read https://github.com/phetsims/proportion/issues/15#issuecomment-613472839

**Comment by Matthew-Moore240** [comment]
understood!
