### ISSUE TITLE
Implement initial mockup

### ISSUE THREAD

**Issue by zepumph** [phetsims/proportion#2]
I received an email from @emily-phet with the initial mockup, so I will put it here:

Mockup description

**Representations**
* two parallel bars - each can be moved up and down independently, but change color (from pink to green) when the ratio of their height is at the target ratio (e.g., 1:2).
* To support initial interaction by learner, on startup there are brightly colored (orange) double-sided arrows (pointing up/down) on top of each bar, that disappear once the user moves the bar.

 **Controls**
* Addition of grid and numbered grid. When grid is selected, a grid overlays the two parallel bars, when numbered grid is selected, numbers are added along one side of the grid (1-10 or something like that). This is represented as radio button group of three radio buttons, first option“none”, second option a small icon of a grid, and third option, an icon of a numbered grid).
* Changing the target proportion value (e.g, from 1:2 to 2:3). There are 3 (or 4) options to select from, represented as scene selection screens (radio button group, with a distinct visual appearance of square tile buttons). The ratios themselves are mysteries for the learner to discover, so the icon each scene selection is a different wrapped gift box with a bow, and a letter on each box (A, B, C, D). 

**Typical PhET sim stuff - all multiscreen PhET sims contain the following:**
* There’s a “reset all” button in the lower right-hand corner
* There is a “nav bar” at the bottom of the screen, which contains the sim Name, home screen icon, sim screen icons, keyboard help button, sound on/off button, and phet menu button.

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/77944456-7d735900-726b-11ea-9869-e6e91d159708.png)

**Comment by zepumph** [comment]
I have gone through the initial mockup and implemented everything (at least at a first pass) except the grid radio buttons, which I was going to wait on until I understood their behavior a bit more (see https://github.com/phetsims/proportion/issues/5). 

@emily-phet please review. I can still work further on this tomorrow to refine for the meeting on Wednesday. just let me know what you would like to do.  

Here is the first dev link of progress from today. https://phet-dev.colorado.edu/html/proportion/1.0.0-dev.1/phet/proportion_en_phet.html

**Comment by BLFiedler** [comment]
Great work!

Four quick thoughts:

- It's possible to drag the bars so low that you can't retrieve them without resetting. 
- There's something wonky about Mystery 3 which I think has to do with the proportion being inverted. At low tolerance, it's possible to never see it (maybe something to do with the number of values on the slider?)
- Definitely could use a grid or number grid option (eventually).
- Great idea on the tolerance option!

**Comment by emily-phet** [comment]
@zepumph Thanks - this great!

By tomorrow's meeting...
- Can you have the sim start in the green state (at the 1:2 ratio?)

**Comment by zepumph** [comment]
>It's possible to drag the bars so low that you can't retrieve them without resetting.

I made a min height so that you can't make the bar smaller than 10% of the bar's height.

>There's something wonky about Mystery 3 which I think has to do with the proportion being inverted. At low tolerance, it's possible to never see it (maybe something to do with the number of values on the slider?)

Yes, the ratio is 4:1, I thought it would be good to flip it one so the other was larger. Perhaps now with a forced min of 10%, it will be easier to set the right proportion.
![image](https://user-images.githubusercontent.com/6856943/78049097-19ae6600-7327-11ea-87ba-efa621fa6aa2.png)

>Great idea on the tolerance option!

I added this mostly just as a design/dev tool. It can help us find the value. I didn't think it would stick around (though it definitely could!). 

>Can you have the sim start in the green state (at the 1:2 ratio?)

Implemented above. Talk to you tomorrow!

**Comment by zepumph** [comment]
I'm going to go ahead and close this issue since a mockup has been created. We can make new issues for further work.
